export const MailIdentityAuditAction = {
  CustomDomainRegistered: "MAIL_IDENTITY_CUSTOM_DOMAIN_REGISTERED",
  CustomDomainDnsVerified: "MAIL_IDENTITY_CUSTOM_DOMAIN_DNS_VERIFIED",
  CustomDomainDnsFailed: "MAIL_IDENTITY_CUSTOM_DOMAIN_DNS_FAILED",
  SenderProvisioned: "MAIL_IDENTITY_SENDER_PROVISIONED",
  DisplayNameUpdated: "MAIL_IDENTITY_DISPLAY_NAME_UPDATED",
  SuppressionAdded: "MAIL_IDENTITY_SUPPRESSION_ADDED",
  SuppressionRemoved: "MAIL_IDENTITY_SUPPRESSION_REMOVED",
  TenantSubdomainProvisioned: "MAIL_IDENTITY_TENANT_SUBDOMAIN_PROVISIONED",
  TenantSubdomainDnsVerified: "MAIL_IDENTITY_TENANT_SUBDOMAIN_DNS_VERIFIED",
  AdminDomainCreated: "MAIL_IDENTITY_ADMIN_DOMAIN_CREATED",
  AdminDomainDnsVerified: "MAIL_IDENTITY_ADMIN_DOMAIN_DNS_VERIFIED",
  AdminDomainManuallyVerified: "MAIL_IDENTITY_ADMIN_DOMAIN_MANUAL_VERIFIED",
  TenantSuspended: "MAIL_TENANT_SUSPENDED",
  TenantUnsuspended: "MAIL_TENANT_UNSUSPENDED",
  PrivacyDataExport: "MAIL_PRIVACY_DATA_EXPORT",
  PrivacyDeletionRequested: "MAIL_PRIVACY_DELETION_REQUESTED",
  PrivacyDeletionCompleted: "MAIL_PRIVACY_DELETION_COMPLETED",
  PrivacyDeletionCancelled: "MAIL_PRIVACY_DELETION_CANCELLED",
  DefaultSenderSet: "MAIL_IDENTITY_DEFAULT_SENDER_SET",
  SubscriptionPlanSelected: "MAIL_SUBSCRIPTION_PLAN_SELECTED",
  TeamInviteCreated: "MAIL_TEAM_INVITE_CREATED",
  TeamInviteRevoked: "MAIL_TEAM_INVITE_REVOKED",
  TeamInviteAccepted: "MAIL_TEAM_INVITE_ACCEPTED",
  TeamMemberRoleChanged: "MAIL_TEAM_MEMBER_ROLE_CHANGED",
  TeamMemberRemoved: "MAIL_TEAM_MEMBER_REMOVED",
  SecurityRequireTotpUpdated: "MAIL_SECURITY_REQUIRE_TOTP_UPDATED",
  SecurityTotpEnabled: "MAIL_SECURITY_TOTP_ENABLED",
  SecurityTotpDisabled: "MAIL_SECURITY_TOTP_DISABLED",
  BrandingUpdated: "MAIL_BRANDING_UPDATED",
  IntegrationApiKeyCreated: "MAIL_INTEGRATION_API_KEY_CREATED",
  IntegrationApiKeyRevoked: "MAIL_INTEGRATION_API_KEY_REVOKED",
  IntegrationWebhookCreated: "MAIL_INTEGRATION_WEBHOOK_CREATED",
  IntegrationWebhookUpdated: "MAIL_INTEGRATION_WEBHOOK_UPDATED",
  MailAliasCreated: "MAIL_ALIAS_CREATED",
  MailAliasRemoved: "MAIL_ALIAS_REMOVED",
} as const;

export type MailIdentityAuditActionCode =
  (typeof MailIdentityAuditAction)[keyof typeof MailIdentityAuditAction];
